"""empty message

Revision ID: 18f842b3ca0b
Revises: 2ca57a8203ba
Create Date: 2015-09-23 15:30:22.312372

"""

# revision identifiers, used by Alembic.
revision = '18f842b3ca0b'
down_revision = '2ca57a8203ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency', sa.Column('stable_version', sa.Unicode(length=36), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependency', 'stable_version')
    ### end Alembic commands ###
