"""empty message

Revision ID: 435c1fb10826
Revises: 472d03a325b0
Create Date: 2015-03-08 16:13:32.648234

"""

# revision identifiers, used by Alembic.
revision = '435c1fb10826'
down_revision = '472d03a325b0'

from alembic import op
import sqlalchemy as sa
from os import urandom

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    config = op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on_premise', sa.Boolean(), nullable=True),
    sa.Column('workdir', sa.String(length=255), nullable=True),
    sa.Column('site_url', sa.Unicode(length=255), nullable=True),
    sa.Column('request_activation', sa.Boolean(), nullable=True),
    sa.Column('ldap_enabled', sa.Boolean(), nullable=True, default=False),
    sa.Column('ldap_url', sa.Unicode(length=255), nullable=True),
    sa.Column('ldap_basedn', sa.Unicode(length=128), nullable=True),
    sa.Column('smtp_server', sa.Unicode(length=255), nullable=True),
    sa.Column('smtp_use_ssl', sa.Boolean(), nullable=True),
    sa.Column('smtp_username', sa.Unicode(length=128), nullable=True),
    sa.Column('smtp_password', sa.Unicode(length=128), nullable=True),
    sa.Column('smtp_from_addr', sa.Unicode(length=128), nullable=True),
    sa.Column('github_enabled', sa.Boolean(), nullable=True, default=False),
    sa.Column('github_client_id', sa.String(length=32), nullable=True),
    sa.Column('github_client_secret', sa.String(length=64), nullable=True),
    sa.Column('github_scope', sa.String(length=128), nullable=True),
    sa.Column('bitbucket_enabled', sa.Boolean(), nullable=True, default=False),
    sa.Column('bitbucket_key', sa.String(length=32), nullable=True),
    sa.Column('bitbucket_secret', sa.String(length=64), nullable=True),
    sa.Column('mailchimp_enabled', sa.Boolean(), nullable=True, default=False),
    sa.Column('mailchimp_api_key', sa.String(length=64), nullable=True),
    sa.Column('mailchimp_list_news', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(config, [
        {
		"id": 1,
		"on_premise": True,
		"request_activation": False,
		"workdir": "/var/lib/dw-workspace",
		"site_url": u"http://localhost:3001"
	}
    ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    ### end Alembic commands ###
