"""empty message

Revision ID: 472d03a325b0
Revises: 1f23788d2c8e
Create Date: 2015-02-23 17:19:17.944364

"""

# revision identifiers, used by Alembic.
revision = '472d03a325b0'
down_revision = '1f23788d2c8e'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency_reference', sa.Column('line', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependency_reference', 'line')
    ### end Alembic commands ###
