"""empty message

Revision ID: aceb5ece89f
Revises: 18f842b3ca0b
Create Date: 2015-12-12 08:13:03.012196

"""

# revision identifiers, used by Alembic.
revision = 'aceb5ece89f'
down_revision = '18f842b3ca0b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from dependencywatcher.website.model import Repository, RepositoryStats
from dependencywatcher.website.webapp import db

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('deps', sa.Integer(), nullable=True),
    sa.Column('outdated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    bind = op.get_bind()
    for repo in db.session.query(Repository):
        repo.stats = RepositoryStats()
        repo.stats.repository_id = repo.id
        repo.stats.update()

    db.session.commit()
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_stats')
    ### end Alembic commands ###
